name: Gradle Dependency Submission

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Use Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout ZK EE
        uses: actions/checkout@v4
        with:
          repository: zkoss/zkcml
          ref: master
          ssh-key: '${{ secrets.SSH_KEY }}'
          path: zkcml-${{ github.run_id }}-${{ github.run_number }}

      - run: |
          mv zkcml-${{ github.run_id }}-${{ github.run_number }} ../zkcml
          cd ../zkcml
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Prepare Gradle settings
        run: |
          sed -i 's/includeBuild/\/\/includeBuild/' settings.gradle

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
