name: WIP
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
  workflow_run:
    workflows: [ "Automatic Rebase Command" ]
    types:
      - completed
    inputs:
      tags: "${{  github.event.pull_request }}"

jobs:
  wip:
    runs-on: ubuntu-latest
    steps:
      - uses: zkoss/wip-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: |
          echo "PR: ${{payload.pull_request}}"
          echo "Tags: ${{ github.event.inputs.tags }}"