name: zk-build

on:
  push:
    branches-ignore:
      - '*-Stable'
  pull_request:
    branches-ignore:
      - '*-Stable'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Use Node.js 16 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout ZK EE
        uses: actions/checkout@v3
        with:
          repository: zkoss/zkcml
          ref: 10-experiment
          path: zkcml-${{ github.run_id }}-${{ github.run_number }}
          ssh-key: '${{ secrets.SSH_KEY }}'
      - run: |
          mv zkcml-${{ github.run_id }}-${{ github.run_number }} ../zkcml
          cd ../zkcml
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - name: Build Latest ZK
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          sed -i 's/includeBuild/\/\/includeBuild/' settings.gradle
          cd eslint-plugin-zk
          npm run build

          cd ..
          ./gradlew build

